package speed.clicks;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author louis
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Intro extends javax.swing.JFrame {
 SpeedClick speedClickF;
 reglesDeJeu rdjFrame;
 
    /**
     * Creates new form Intro
     */
    public Intro() {
        initComponents();
        Start.setEnabled(false);
    }
    
    
    private void startButtonEnabled(){
        boolean checkboxSelected = Debutant.isSelected() || Intermediaire.isSelected() || Confirme.isSelected() || Avance.isSelected();
        Start.setEnabled(checkboxSelected);
    }
    
    public boolean isDebutantSelected(){
        return Debutant.isSelected();
    }
    
    public JCheckBox getIntermediaireCheckBox(){
        return Intermediaire;
    }
    
    public void setIntermediaireEnabled(boolean enabled){
       Intermediaire.setEnabled(enabled);
    }
    public boolean isIntermediaireSelected(){
        return Intermediaire.isSelected();
    }
    public boolean isConfirmeSelected(){
        return Confirme.isSelected();
    }
     public boolean isAvanceSelected(){
        return Avance.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Debutant = new javax.swing.JCheckBox();
        Confirme = new javax.swing.JCheckBox();
        Intermediaire = new javax.swing.JCheckBox();
        Avance = new javax.swing.JCheckBox();
        Start = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rdjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to our game Speed-Click");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 690, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHOOSE THE LEVEL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        UserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 240, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First step: What is your name?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        Debutant.setForeground(new java.awt.Color(255, 255, 255));
        Debutant.setText("Débutant");
        jPanel1.add(Debutant, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 20));

        Confirme.setForeground(new java.awt.Color(255, 255, 255));
        Confirme.setText("Confirmé");
        Confirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmeActionPerformed(evt);
            }
        });
        jPanel1.add(Confirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, 20));

        Intermediaire.setForeground(new java.awt.Color(255, 255, 255));
        Intermediaire.setText("Intermediaire");
        jPanel1.add(Intermediaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, 20));

        Avance.setForeground(new java.awt.Color(255, 255, 255));
        Avance.setText("Avancé");
        jPanel1.add(Avance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, 20));

        Start.setBackground(new java.awt.Color(0, 0, 0));
        Start.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        Start.setForeground(new java.awt.Color(255, 255, 255));
        Start.setText("START");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 445, 140, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REGLES DU JEU !");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 200, 40));

        rdjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rdjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speed/clicks/resources/Menu.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel4.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 1110, 860));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 790, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
       speedClickF = new SpeedClick(this);
       speedClickF.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_StartActionPerformed
    private void DebutantActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if (speedClickF != null){
           speedClickF.setPanelGrilleTaille(5);
       }
       startButtonEnabled();
    }                                        
    private void IntermediaireActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if (speedClickF != null){
           speedClickF.setPanelGrilleTaille(10);
       }
       startButtonEnabled();
    } 
    private void ConfirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmeActionPerformed
       if (speedClickF != null){
           speedClickF.setPanelGrilleTaille(10);
       }
       startButtonEnabled();
    }//GEN-LAST:event_ConfirmeActionPerformed

    private void AvanceActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if (speedClickF != null){
           speedClickF.setPanelGrilleTaille(10);
       }
       startButtonEnabled();
    }     
    private void rdjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdjButtonActionPerformed
        rdjFrame= new reglesDeJeu();
        rdjFrame.setVisible(true);
    }//GEN-LAST:event_rdjButtonActionPerformed
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Avance;
    private javax.swing.JCheckBox Confirme;
    private javax.swing.JCheckBox Debutant;
    private javax.swing.JCheckBox Intermediaire;
    private javax.swing.JButton Start;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rdjButton;
    // End of variables declaration//GEN-END:variables

    
}
