package speed.clicks;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;  
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;


/**
 *
 * @author louis
 */
public class JeuSpeedClick extends javax.swing.JFrame {
   
    
    int score;
    JButton[][] boutons;    
    Timer chrono;
    JLabel scoreLab;
    int countdown;
    JLabel cdLab;
    /**
     * Creates new form JeuSpeedClick
     */
    public JeuSpeedClick() {
        setTitle("Speed Click Game");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600,600);
        
         JPanel infoPanel = new JPanel (new BorderLayout());
         setContentPane(infoPanel);
        
         scoreLab = new JLabel("Score: 0",SwingConstants.CENTER);
         cdLab = new JLabel ("Countdown: 30", SwingConstants.CENTER);
        cdLab.setFont(new Font("SanSerif", Font.PLAIN, 12));
         
        JPanel scoreEtCdPanel = new JPanel (new GridLayout(1,2));
        scoreEtCdPanel.add(scoreLab);
        scoreEtCdPanel.add(cdLab);
        infoPanel.add(scoreEtCdPanel, BorderLayout.NORTH);
        
       
        
        boutons= new JButton[5][5];
        JPanel PanelGrille = new JPanel (new GridLayout (5,5));
        infoPanel.add(PanelGrille, BorderLayout.CENTER);
      
        chrono= new Timer(1000, new ActionListener(){
            @Override
             public void actionPerformed(ActionEvent e){
               countdown--;
               updateCountdownLabel();
               if (countdown ==0){
                stopGame();
            JOptionPane.showMessageDialog(JeuSpeedClick.this, "The Game Is Over! : "+score);
            startGame();
               }
             }       
        });
    
    
    
   
        /*JPanel panel = new JPanel (new GridLayout(TailleGrille, TailleGrille));*/
        for (int i = 0; i< 5; i++){
           for (int j = 0; j< 5; j++) {
            boutons[i][j]= new JButton();
             boutons[i][j].setBackground(Color.BLUE);
             
             boutons[i][j].addActionListener( new ButtonClickListener());
            
             
            PanelGrille.add(boutons[i][j]);
           }
        }
        
       /* scoreLab = new JLabel ("Score: 0", SwingConstants.CENTER);
        infoPanel.add(scoreLab, BorderLayout.NORTH);*/
        
        
        
startGame();


setVisible(true);
    }
 
               
 
    private void updateCountdownLabel(){
        cdLab.setText("Countdown: "+countdown);
    }      
    
   
    
    
    
    private class ButtonClickListener implements ActionListener {
        @Override
                public void actionPerformed (ActionEvent e){
        JButton clicked = (JButton) e.getSource();
        if (clicked.getBackground() == Color.RED){
            score++;
            clicked.setBackground(Color.BLUE);
            changerBoutonAllume();
            updateScoreLabel();
        }else{
            
            stopGame();
            JOptionPane.showMessageDialog(JeuSpeedClick.this, "The Game Is Over! : "+score);
            startGame();
        }
        }
        
    }
    private void changerBoutonAllume(){
        Random rand = new Random();
        int lAllumee = rand.nextInt(5);
        int cAllumee = rand.nextInt(5);
        
        for (int i = 0; i< 5; i++){
           for (int j = 0; j< 5; j++) {
               boutons [i][j].setBackground(Color.BLUE);
           }
    }
        boutons[lAllumee][cAllumee].setBackground(Color.RED);
        
    }
  private void startGame() {
      score =0;
      countdown =30;
      updateScoreLabel();
      updateCountdownLabel();
      changerBoutonAllume();
      chrono.start();
    
        
    }

   
   
    private void stopGame(){
        chrono.stop();
    }
  private void updateScoreLabel(){
      scoreLab.setText("Score: "+score);
  }
   
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGrille = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JPanel();
        cdLabel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGrille.setBackground(new java.awt.Color(255, 204, 204));
        PanelGrille.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout PanelGrilleLayout = new javax.swing.GroupLayout(PanelGrille);
        PanelGrille.setLayout(PanelGrilleLayout);
        PanelGrilleLayout.setHorizontalGroup(
            PanelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        PanelGrilleLayout.setVerticalGroup(
            PanelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        scoreLabel.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout scoreLabelLayout = new javax.swing.GroupLayout(scoreLabel);
        scoreLabel.setLayout(scoreLabelLayout);
        scoreLabelLayout.setHorizontalGroup(
            scoreLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        scoreLabelLayout.setVerticalGroup(
            scoreLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        cdLabel.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout cdLabelLayout = new javax.swing.GroupLayout(cdLabel);
        cdLabel.setLayout(cdLabelLayout);
        cdLabelLayout.setHorizontalGroup(
            cdLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        cdLabelLayout.setVerticalGroup(
            cdLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PanelGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeuSpeedClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeuSpeedClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeuSpeedClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeuSpeedClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeuSpeedClick().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGrille;
    private javax.swing.JPanel cdLabel;
    private javax.swing.JPanel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
